# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: 'Instalar modulos'
        run: npm install
      - name: 'Inicia servidor node'
        run: npm start & 
      - name: 'Pruebas métodos jorge en local'
        run: npm run test-jorge-local
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    
      - name: Deploy
        run: gcloud app deploy
      - name: 'Esperar antes de ejecutar las pruebas'
        run: sleep 15
      - name: 'Pruebas métodos jorge en gcloud'
        run: npm run test-jorge-gcloud
