# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: 'Instalar modulos'
        run: npm install
      - name: 'Actualizando frontend producción'
        run: cd frontend; npm run build;cd ..
      - name: 'Inicia servidor node'
        run: npm start & 
      - name: 'Pruebas métodos en local'
        run: npm test
      
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    
      - name: Deploy
        run: gcloud app deploy
      - name: 'Esperar antes de ejecutar las pruebas de gcloud'
        run: sleep 15
      - name: 'Pruebas métodos en gcloud'
        run: npm run test-gcloud